# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ff0ee9a6df39edf90b4a224ab1690a5fe39568d3d2bab8167ad1a1ba3d93eb107c42b287659100b159f64dc64cb0ce7be36c418f497e24fa7ec29d5aaab5d9

test:
  secret_key_base: fa1ec8d8f310f3604613f0843e6bc156b22b860e5229fca1d719c36b37473df073f52fa743bb83840cdea957050bd645fdcf08dda6b2657ce0e7a8361d05773d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
